baseURL = 'https://nathanlaundry.com/'
languageCode = 'en-us'
title = "Nathan Laundry's Blog"
theme = 'smol'

pluralizeListTitles = false

# Parameters
[params]
    subtitle = "hackin on homelab stuff, some self-improvement, a little poetry, and occasionally an academic publication"
    dateFmt = "02.01.2006 15:04"
    mainSections = ["lifeandlab", "shower-thoughts", "tech", "poetry", "talks", "publications"]

[markup.goldmark.renderer]
    hardWraps = true
    unsafe = true

# Header
[menu]
  [[menu.main]]
        identifier = "Life and Lab"
        name = "Life and Lab"
        url = "/lifeandlab/"
        weight = 1 
  [[menu.main]]
        identifier = "Shower-Thoughts"
        name = "Shower Thoughts"
        url = "/shower-thoughts/"
        weight = 1 
  [[menu.main]]
        identifier = "Tech"
        name = "Tech"
        url = "/tech/"
        weight = 2
  [[menu.main]]
        identifier = "Poetry"
        name = "Poetry"
        url = "/poetry/"
        weight = 3
  [[menu.main]]
        identifier = "Talks"
        name = "Talks"
        url = "/talks/"
        weight = 4
  [[menu.main]]
        identifier = "Publications"
        name = "Publications"
        url = "/publications/"
        weight = 5

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/NLaundry"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://example.com/@user"
        weight = 2 

    [[menu.fotter]]
        name = "Medium"
        url = "https://medium.com/@user"
        weight = 3
    [[menu.footer]]
        name = "Substack"
        url = "https://example.substack.com"
        weight = 4
